stages:
  - build


win_build:
  stage: build
  tags:
    - MBED_TEST
  script:
    - cd
    - git submodule update --init
    - cd boot/cypress
    - C:/msys64/usr/bin/make.exe app APP_NAME=MCUBootApp TARGET=CY8CPROTO-062-4343W-M0 BUILDCFG=Debug TOOLCHAIN=C:/Users/cydesigner/ModusToolbox/tools_2.0/gcc-7.2.1
    

mac_build:
  stage: build
  tags:
    - MBED_TEST_MAC1014
  script:
    - export https_proxy=http://proxy.ua.cypress.com:8080
    - pwd
    - git submodule update --init
    - cd boot/cypress
    - make app APP_NAME=MCUBootApp TARGET=CY8CPROTO-062-4343W-M0 BUILDCFG=Debug TOOLCHAIN=/Applications/ModusToolbox/tools_2.0/gcc-7.2.1


lin_build:
  stage: build
  tags:
    - FW_SECURITY_TEST_UBUNTU1804
  script:
    - export https_proxy=http://proxy.ua.cypress.com:8080
    - pwd
    - git submodule update --init
    - cd boot/cypress
    - make app APP_NAME=MCUBootApp TARGET=CY8CPROTO-062-4343W-M0 BUILDCFG=Debug TOOLCHAIN=/Applications/ModusToolbox/tools_2.0/gcc-7.2.1
    
